version: '3.6'

services:
    mysql1:
        image: mysql/mysql-server:8.0
        environment:
            MYSQL_ROOT_PASSWORD: chamados
        ports:
            - "127.0.0.1:3306:3306"
        expose:
            - "3306"
        networks:
            - bridge
    myapp:
        build:
            context: .
            dockerfile: Dockerfile
        command: npm start
        depends_on:
            - mysql1
        ports:
            - "127.0.0.1:5000:5000"
        expose:
            - "5000"
        links:
            - mysql1
        networks:
            - bridge

networks:
    bridge:
        driver: bridge
        driver_opts: 
            com.docker.network.bridge.host_binding_ipv4": "0.0.0.0"